# fly.toml app configuration file generated for quiet-snow-8383 on 2023-05-09T07:20:47-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "quiet-snow-8383"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
