# fly.toml app configuration file generated for tryoneagain2 on 2023-12-17T22:20:36-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tryoneagain2"
primary_region = "lax"
kill_timeout = "5m0s"

[build]

[http_service]
  internal_port = 5432
  force_https = true
  auto_start_machines = true
