# fly.toml app configuration file generated for falling-surf-7159 on 2023-12-18T21:17:22-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "falling-surf-7159"
primary_region = "atl"

[build]

[http_service]
  internal_port = 5432
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
