# fly.toml app configuration file generated for white-moon-2294 on 2023-05-09T07:21:42-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "white-moon-2294"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true
